spring.application.name=sport-saas
spring.datasource.url=jdbc:mysql://localhost:3306/sport_saas
spring.datasource.username=sport_saas
spring.datasource.password=sport_saas_dev
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true